name: ci

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: diebietse/invertergui
      DOCKER_TARGET_PLATFORM: linux/amd64,linux/386,linux/arm64,linux/arm/v7

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::$(git describe --tags --always --dirty  | tr -d '\n')

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ steps.prepare.outputs.docker_platform }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ steps.prepare.outputs.docker_platform }}
          push: true
          tags: ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}
